[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.web]
    address=":80"
[providers.file]
  directory="/home/vagrant/traefik-config/services/"
  watch=true 
