[http]
 [http.routers]
   [http.routers.main_route]
     entryPoints = ["web"]
     service = "main_service"
     rule = "Path(`/`)"
 [http.services]
    [http.services.main_service.loadBalancer]
      [[http.services.main_service.loadBalancer.servers]]
        url = "http://172.18.1.3"
      [[http.services.main_service.loadBalancer.servers]]
        url = "http://172.18.1.4"
      [[http.services.main_service.loadBalancer.servers]]
        url = "http://172.18.1.5"
