version: "3"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx-service
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: "Host(`nginx.service.com`)"
      traefik.http.services.nginx.loadbalancer.server.port: 80
      traefik.http.routers.nginx.service: nginx
      traefik.port: 80
      traefik.http.routers.nginx.entrypoints: web
    volumes:
      - ${PWD}/example.com-index.html:/usr/share/nginx/html/index.html
    networks:
    - app_net

  tomcat:
    container_name: tomcat-service
    image: tomcat:alpine
    labels:
     traefik.enable: true
    volumes:
      - ${PWD}/sample.war:/usr/share/tomcat/webapps/sample.war
    networks:
    - app_net

  mysqldb:
    container_name: mysql-service
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD="SuperSecretPassword"
    networks:
    - app_net
        

networks:
  app_net:
   external: true
